clc;
clear all;
close all;

mult1=zeros(10,10,16);
mult1=int8(mult1);
imgx =textread("D:\matlab_read\L3_F1_file.txt",'%s')


imgx=signedhex_2_signeddec(imgx);
imgx=reshape(imgx,10,10);
%imgx=rot90(imgx,3);
imgx=imgx.';
imgx=int8(imgx);
mult1(:,:,1)=imgx;

imgx =textread("D:\matlab_read\L3_F2_file.txt",'%s');
imgx=signedhex_2_signeddec(imgx);
imgx=reshape(imgx,10,10);
%imgx=rot90(imgx,3);
imgx=imgx.';
imgx=int8(imgx);
mult1(:,:,2)=imgx;

imgx =textread("D:\matlab_read\L3_F3_file.txt",'%s');
imgx=signedhex_2_signeddec(imgx);
imgx=reshape(imgx,10,10);
%imgx=rot90(imgx,3);
imgx=imgx.';
imgx=int8(imgx);
mult1(:,:,3)=imgx;

imgx =textread("D:\matlab_read\L3_F4_file.txt",'%s');
imgx=signedhex_2_signeddec(imgx);
imgx=reshape(imgx,10,10);
%imgx=rot90(imgx,3);
imgx=imgx.';
imgx=int8(imgx);
mult1(:,:,4)=imgx;

imgx =textread("D:\matlab_read\L3_F5_file.txt",'%s');
imgx=signedhex_2_signeddec(imgx);
imgx=reshape(imgx,10,10);
%imgx=rot90(imgx,3);
imgx=imgx.';
imgx=int8(imgx);
mult1(:,:,5)=imgx;

imgx =textread("D:\matlab_read\L3_F6_file.txt",'%s');
imgx=signedhex_2_signeddec(imgx);
imgx=reshape(imgx,10,10);
%imgx=rot90(imgx,3);
imgx=imgx.';
imgx=int8(imgx);
mult1(:,:,6)=imgx;

imgx =textread("D:\matlab_read\L3_F7_file.txt",'%s');
imgx=signedhex_2_signeddec(imgx);
imgx=reshape(imgx,10,10);
%imgx=rot90(imgx,3);
imgx=imgx.';
imgx=int8(imgx);
mult1(:,:,7)=imgx;

imgx =textread("D:\matlab_read\L3_F8_file.txt",'%s');
imgx=signedhex_2_signeddec(imgx);
imgx=reshape(imgx,10,10);
%imgx=rot90(imgx,3);
imgx=imgx.';
imgx=int8(imgx);
mult1(:,:,8)=imgx;
imgx =textread("D:\matlab_read\L3_F9_file.txt",'%s');
imgx=signedhex_2_signeddec(imgx);
imgx=reshape(imgx,10,10);
%imgx=rot90(imgx,3);
imgx=imgx.';
imgx=int8(imgx);
mult1(:,:,9)=imgx;
imgx =textread("D:\matlab_read\L3_F10_file.txt",'%s');
imgx=signedhex_2_signeddec(imgx);
imgx=reshape(imgx,10,10);
%imgx=rot90(imgx,3);
imgx=imgx.';
imgx=int8(imgx);
mult1(:,:,10)=imgx;
imgx =textread("D:\matlab_read\L3_F11_file.txt",'%s');
imgx=signedhex_2_signeddec(imgx);
imgx=reshape(imgx,10,10);
%imgx=rot90(imgx,3);
imgx=imgx.';
imgx=int8(imgx);
mult1(:,:,11)=imgx;
imgx =textread("D:\matlab_read\L3_F12_file.txt",'%s');
imgx=signedhex_2_signeddec(imgx);
imgx=reshape(imgx,10,10);
%imgx=rot90(imgx,3);
imgx=imgx.';
imgx=int8(imgx);
mult1(:,:,12)=imgx;
imgx =textread("D:\matlab_read\L3_F13_file.txt",'%s');
imgx=signedhex_2_signeddec(imgx);
imgx=reshape(imgx,10,10);
%imgx=rot90(imgx,3);
imgx=imgx.';
imgx=int8(imgx);
mult1(:,:,13)=imgx;
imgx =textread("D:\matlab_read\L3_F14_file.txt",'%s');
imgx=signedhex_2_signeddec(imgx);
imgx=reshape(imgx,10,10);
%imgx=rot90(imgx,3);
imgx=imgx.';
imgx=int8(imgx);
mult1(:,:,14)=imgx;
imgx =textread("D:\matlab_read\L3_F15_file.txt",'%s');
imgx=signedhex_2_signeddec(imgx);
imgx=reshape(imgx,10,10);
%imgx=rot90(imgx,3);
imgx=imgx.';
imgx=int8(imgx);
mult1(:,:,15)=imgx;
imgx =textread("D:\matlab_read\L3_F16_file.txt",'%s');
imgx=signedhex_2_signeddec(imgx);
imgx=reshape(imgx,10,10);
%imgx=rot90(imgx,3);
imgx=imgx.';
imgx=int8(imgx);
mult1(:,:,16)=imgx;
mult1=double(mult1);

figure(1);
subplot(4,4,1);
imshow(mult1(:,:,1));
title('verilog第二次卷积结果1');
subplot(4,4,2);
imshow(mult1(:,:,2));
title('verilog第二次卷积结果2');
subplot(4,4,3);
imshow(mult1(:,:,3));
title('verilog第二次卷积结果3');
subplot(4,4,4);
imshow(mult1(:,:,4));
title('verilog第二次卷积结果4');
subplot(4,4,5);
imshow(mult1(:,:,5));
title('verilog第二次卷积结果5');
subplot(4,4,6);
imshow(mult1(:,:,6));
title('verilog第二次卷积结果6');

subplot(4,4,7);
imshow(mult1(:,:,7));
title('verilog第二次卷积结果7');
subplot(4,4,8);
imshow(mult1(:,:,8));
title('verilog第二次卷积结果8');
subplot(4,4,9);
imshow(mult1(:,:,9));
title('verilog第二次卷积结果9');
subplot(4,4,10);
imshow(mult1(:,:,10));
title('verilog第二次卷积结果10');
subplot(4,4,11);
imshow(mult1(:,:,11));
title('verilog第二次卷积结果11');
subplot(4,4,12);
imshow(mult1(:,:,12));
title('verilog第二次卷积结果12');
subplot(4,4,13);
imshow(mult1(:,:,13));
title('verilog第二次卷积结果13');
subplot(4,4,14);
imshow(mult1(:,:,14));
title('verilog第二次卷积结果14');
subplot(4,4,15);
imshow(mult1(:,:,15));
title('verilog第二次卷积结果15');
subplot(4,4,16);
imshow(mult1(:,:,16));
title('verilog第二次卷积结果16');

lay_out_03=textread("C:\Users\96348\Desktop\课题相关\FPGA-cnn\CNN_data\5\dat_save\lay3_dat.txt",'%s');
 lay_out_03=hex2dec(lay_out_03);
 lay_out_03=int8(lay_out_03);
 lay_out_03=reshape(lay_out_03,10,10,16)
 lay_out_03=permute(lay_out_03,[2,1,3]);
 lay_out_03=double(lay_out_03);

figure(2);
subplot(4,4,1);
imshow(lay_out_03(:,:,1));
title('参考第二次卷积结果1');
subplot(4,4,2);
imshow(lay_out_03(:,:,2));
title('参考第二次卷积结果2');
subplot(4,4,3);
imshow(lay_out_03(:,:,3));
title('参考第二次卷积结果3');
subplot(4,4,4);
imshow(lay_out_03(:,:,4));
title('参考第二次卷积结果4');
subplot(4,4,5);
imshow(lay_out_03(:,:,5));
title('参考第二次卷积结果5');
subplot(4,4,6);
imshow(lay_out_03(:,:,6));
title('参考第二次卷积结果6');

subplot(4,4,7);
imshow(lay_out_03(:,:,7));
title('参考第二次卷积结果7');
subplot(4,4,8);
imshow(lay_out_03(:,:,8));
title('参考第二次卷积结果8');
subplot(4,4,9);
imshow(lay_out_03(:,:,9));
title('参考第二次卷积结果9');
subplot(4,4,10);
imshow(lay_out_03(:,:,10));
title('参考第二次卷积结果10');
subplot(4,4,11);
imshow(lay_out_03(:,:,11));
title('参考第二次卷积结果11');
subplot(4,4,12);
imshow(lay_out_03(:,:,12));
title('参考第二次卷积结果12');
subplot(4,4,13);
imshow(lay_out_03(:,:,13));
title('参考第二次卷积结果13');
subplot(4,4,14);
imshow(lay_out_03(:,:,14));
title('参考第二次卷积结果14');
subplot(4,4,15);
imshow(lay_out_03(:,:,15));
title('参考第二次卷积结果15');
subplot(4,4,16);
imshow(lay_out_03(:,:,16));
title('参考第二次卷积结果16');
diff=lay_out_03-mult1
